version: 2

jobs:
  build_and_test:
    working_directory: ~/gravnic-game
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install yarn
          command: npm install --global yarn
      - restore_cache:
          keys:
            - gravnic-v2-{{ checksum "yarn.lock" }}
            - gravnic-v2-
      - run:
          name: Install dependancies
          command: yarn
      - save_cache:
          key: gravnic-v2-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Run linter
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test
      - persist_to_workspace:
          root: ~/gravnic-game