version: 2

install_node: &install_node
  name: Install Node
  user: root
  command: |
    set +e             
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
    export NVM_DIR="/opt/circleci/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    nvm install v9.11.1
    nvm alias default v9.11.1
    
    # Each step uses the same `$BASH_ENV`, so need to modify it
    echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
    echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV

install_yarn: &install_yarn
  name: Install yarn
  command: npm install --global yarn

jobs:
  test_build:
    machine: true
    environment:
      ENVIRONMENT: ci
      TERM: xterm-color
    working_directory: ~/gravnic-game
    steps:
      - checkout
      - run:
          <<: *install_node
      - run:
          <<: *install_yarn
      - restore_cache:
          keys:
            - gravnic-v2-{{ checksum "yarn.lock" }}
            - gravnic-v2-
      - run:
          name: Install dependancies
          command: yarn
      - save_cache:
          key: gravnic-v2-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Run linter
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: ~/gravnic-game
          paths: .

  deploy:
    machine: true
    environment:
      ENVIRONMENT: ci
      TERM: xterm-color
    working_directory: ~/gravnic-game
    steps:
      - attach_workspace:
          at: ~/gravnic-game
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/gravnic-game/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test_build
      - deploy:
          requires:
            - test_build
          filters:
            branches:
              only: master